# -----------------------------------------------------------------------------
# .SYNOPSIS
#   This is the main pipeline for Private AKS Deployment. 
#   The main pipeline will orchestrate the build and deploy to environments. 

# .DESCRIPTION
#   This pipeline will perform setup tasks for the image by:
#   1. Copy and Publish Build Artifacts - Terraform scripts.
#   2. Create Storage Account or Terraform State - https://docs.microsoft.com/en-us/azure/terraform/terraform-backend
#   3. Find and replace token (variables) in .tf and .tfvars files.
#   4. Setup Terraform
#   5. Plan and Apply Terraform

# .ASSUMPTIONS:
#     1. You are referencing this template from an ado pipeline

# .NOTES
#     File Name      : azure-pipelines.yml
#     Prerequisite   : ADO Multi-Stage Yaml Pipeline
# -----------------------------------------------------------------------------

name: AKS-Infra-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - infra/private-aks/*
    exclude:
      - README.md

variables:
  - group: aks_dev_vars

  - name: ado_agent_pool
    value: 'UbuntuPrivatePool'
  - name: ado_service_connection_name
    value: 'Azure Subscription'

stages: 
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: ${{variables.ado_agent_pool }}
        steps:
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(build.artifactstagingdirectory)/terraform'
          inputs:
            SourceFolder: 'infra/private-aks'
            TargetFolder: '$(build.artifactstagingdirectory)/terraform'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: infra'
          inputs:
            ArtifactName: infra

  - stage: dev
    displayName: dev
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          name: ${{variables.ado_agent_pool }}
        steps:   
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'infra'
            downloadPath: '$(System.DefaultWorkingDirectory)/_artifacts'

        - task: AzureCLI@1
          displayName: 'Azure CLI to deploy required Azure AKS Preview Extension'
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            scriptLocation: inlineScript
            inlineScript: |
              az extension add --name aks-preview
              
              # Update the extension to make sure you have the latest version installed
              
              az extension update --name aks-preview
              
              az feature register --name AKSPrivateLinkPreview --namespace Microsoft.ContainerService
              
              az feature register --name MSIPreview --namespace Microsoft.ContainerService
              
              az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/AKSPrivateLinkPreview')].{Name:name,State:properties.state}"
              
              az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/MSIPreview')].{Name:name,State:properties.state}"
              
              az provider register --namespace Microsoft.ContainerService
              
              az provider register --namespace Microsoft.Network

              az provider register --namespace Microsoft.ContainerRegistry
                
        # This task is disabled and value is set in the variable group. Due to insuficient permissions issues of the service principal. 
        - task: AzureCLI@1
          displayName: 'Azure CLI to get Service Principal ID'
          enabled: false 
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            scriptLocation: inlineScript
            inlineScript: |
              # Set Service Principal ID as Variable for later use
              echo "##vso[task.setvariable variable=aks_service_principal_id]$(az ad app show --id $(aks_service_principal_client_id) --query "objectId" -o tsv))"
              
        - task: AzureCLI@1
          displayName: 'Azure CLI to deploy required Azure resources (Terraform State)'
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            scriptLocation: inlineScript
            inlineScript: |
              echo "Create Azure resource group - $(terraformstoragerg)"
              az group create -l $(location) -n $(terraformstoragerg)
              
              echo "Create Azure Storage Account $(terraformstorageaccount) - $(location)"
              az storage account create -n $(terraformstorageaccount) -g $(terraformstoragerg) -l $(location) --sku Standard_LRS --kind StorageV2
              
              echo "Create Storage Container"
              az storage container create --name terraform --account-name $(terraformstorageaccount)
              
              echo "Create and set Private Endpoint connection to Storage Account"
              az network vnet subnet update --ids $(az network vnet subnet show --name $(pe_subnet_name) --resource-group $(pe_rg_name) --vnet-name $(pe_vnet_name) --query "id" -o tsv) --disable-private-endpoint-network-policies true

              az network private-endpoint create --name "$(terraformstorageaccount)-pe" --resource-group $(terraformstoragerg) --subnet $(az network vnet subnet show --name $(pe_subnet_name) --resource-group $(pe_rg_name) --vnet-name $(pe_vnet_name) --query "id" -o tsv) --private-connection-resource-id $(az storage account show -g $(terraformstoragerg) -n $(terraformstorageaccount) --query "id" -o tsv) --group-ids blob --connection-name "$(terraformstorageaccount)-blobconnection" --manual-request false
              
              echo "Get Storage Key"
              set KEY=$(az storage account keys list -g $(terraformstoragerg) -n $(terraformstorageaccount) --query "[0].value" -o tsv)
              
              echo "Set Storage Key as Variable for later use"
              echo "##vso[task.setvariable variable=storagekey]$KEY"
        
        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in terraform file'
          inputs:
            targetFiles: '**/*.tf'
            escapeType: none
            tokenPrefix: '__'
            tokenSuffix: '__'

        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in terraform vars file'
          inputs:
            targetFiles: '**/*.tfvars'
            escapeType: none
            tokenPrefix: '__'
            tokenSuffix: '__'
          
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          displayName: 'Install Terraform 0.12.20'
          inputs:
            terraformVersion: 0.12.20

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : init'
          inputs:
            workingDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/infra'
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: terraform
            backendAzureRmKey: terraform.tfstate
              
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : plan'
          inputs:
            command: plan
            workingDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/infra/terraform'
            environmentServiceNameAzureRM: ${{ variables.ado_service_connection_name }}
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: terraform
            backendAzureRmKey: terraform.tfstate

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : apply -auto-approve'
          inputs:
            command: apply
            workingDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/infra/terraform'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: ${{ variables.ado_service_connection_name }}
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: terraform
            backendAzureRmKey: terraform.tfstate
