# -----------------------------------------------------------------------------
# .SYNOPSIS
#   This is the main pipeline for Private AKS Deployment. 
#   The main pipeline will orchestrate the build and deploy to environments. 

# .DESCRIPTION
#   This pipeline will perform setup tasks for the image by:
#   1. Copy and Publish Build Artifacts - Terraform scripts.
#   2. Create Storage Account or Terraform State - https://docs.microsoft.com/en-us/azure/terraform/terraform-backend
#   3. Find and replace token (variables) in .tf and .tfvars files.
#   4. Setup Terraform
#   5. Plan and Apply Terraform

# .ASSUMPTIONS:
#     1. You are referencing this template from an ado pipeline

# .NOTES
#     File Name      : azure-pipelines.yml
#     Prerequisite   : ADO Multi-Stage Yaml Pipeline
# -----------------------------------------------------------------------------

name: AKS-Infra-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - infra/*
      - pipelines/infra/*
    exclude:
      - /**/*.md
      - /**/*.sh
      - /**/LICENSE

variables:
  - template: /pipelines/variables.yml

stages: 
  - stage: Build
    displayName: Build
    jobs:
    - template: /pipelines/infra/build.yml
      parameters:
        environment: Build

  - stage: DEV
    displayName: DEV
    dependsOn: Build
    variables:
      - template: /pipelines/variables.dev.yml
    jobs:
    - template: /pipelines/infra/deploy.yml
      parameters:
        environment: ${{ variables.environment }}
        ado_service_connection_name: ${{ variables.ado_service_connection_name }}
        
  - stage: PRD
    displayName: PRD
    dependsOn: DEV
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      - template: /pipelines/variables.prd.yml
    jobs:
    - template: /pipelines/infra/deploy.yml
      parameters:
        environment: ${{ variables.environment }}
        ado_service_connection_name: ${{ variables.ado_service_connection_name }}
    

