parameters:
- name: environment
  type: string
  displayName: 'The environment name'

- name: dependsOn
  type: string
  displayName: 'The components this job depends on like another job'
  default: ''

jobs:
- job: ${{ parameters.environment }}
  dependsOn: ${{ parameters.dependsOn }}
  displayName: ${{ parameters.environment }}
  steps:   
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)/private-aks'
      inputs:
        SourceFolder: 'infra'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: infra'
      inputs:
        ArtifactName: infra

    