parameters:
- name: environment
  type: string
  displayName: 'The environment name'

- name: ado_service_connection_name
  type: string
  displayName: 'The Service Connection to run Stage'

- name: dependsOn
  type: string
  displayName: 'The components this job depends on like another job'
  default: ''

jobs:
- deployment: ${{ parameters.environment }}
  dependsOn: ${{ parameters.dependsOn }}
  displayName: Deploy
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'infra'
            downloadPath: '$(System.DefaultWorkingDirectory)/_artifacts'

        - task: AzureCLI@1
          displayName: 'Azure CLI to deploy required Azure AKS Preview Extension'
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            scriptLocation: inlineScript
            inlineScript: |
              az extension add --name aks-preview
              
              # Update the extension to make sure you have the latest version installed
              
              az extension update --name aks-preview
              
              az feature register --name AKSPrivateLinkPreview --namespace Microsoft.ContainerService
              
              az feature register --name MSIPreview --namespace Microsoft.ContainerService
              
              az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/AKSPrivateLinkPreview')].{Name:name,State:properties.state}"
              
              az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/MSIPreview')].{Name:name,State:properties.state}"
              
              az provider register --namespace Microsoft.ContainerService
              
              az provider register --namespace Microsoft.Network

              az provider register --namespace Microsoft.ContainerRegistry
                          
        - task: AzureCLI@1
          displayName: 'Azure CLI to deploy required Azure resources (Terraform State)'
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            scriptLocation: inlineScript
            inlineScript: |
              echo "Get Storage Key"
              set KEY=$(az storage account keys list -g $(terraformstoragerg) -n $(terraformstorageaccount) --query "[0].value" -o tsv)
              
              echo "Set Storage Key as Variable for later use"
              echo "##vso[task.setvariable variable=storagekey]$KEY"
        
        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in terraform vars file'
          inputs:
            targetFiles: '$(System.DefaultWorkingDirectory)/_artifacts/infra/*.tfvars'
            escapeType: none
            tokenPrefix: '__'
            tokenSuffix: '__'
          
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          displayName: 'Install Terraform 0.12.24'
          inputs:
            terraformVersion: 0.12.24

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : init'
          inputs:
            workingDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/infra'
            commandOptions: '-reconfigure'
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: '$(terraformstoragecontainer)'
            backendAzureRmKey: '$(terraformstorageblobname)'
              
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : plan'
          inputs:
            command: plan
            workingDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/infra'
            environmentServiceNameAzureRM: ${{ variables.ado_service_connection_name }}
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: '$(terraformstoragecontainer)'
            backendAzureRmKey: '$(terraformstorageblobname)'

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : apply'
          inputs:
            command: apply
            workingDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/infra'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: ${{ variables.ado_service_connection_name }}
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: '$(terraformstoragecontainer)'
            backendAzureRmKey: '$(terraformstorageblobname)'
