# -----------------------------------------------------------------------------
# .SYNOPSIS
#   This is the main pipeline for Bastion Deployment. 
#   The main pipeline will orchestrate the build and deploy to environments. 

# .DESCRIPTION
#   This pipeline will perform setup tasks for the image by:
#   1. Copy and Publish Build Artifacts - Terraform scripts.
#   2. Create Storage Account or Terraform State - https://docs.microsoft.com/en-us/azure/terraform/terraform-backend
#   3. Find and replace token (variables) in .tf and .tfvars files.
#   4. Setup Terraform
#   5. Plan and Apply Terraform

# .ASSUMPTIONS:
#     1. You are referencing this template from an ado pipeline

# .NOTES
#     File Name      : azure-pipelines.yml
#     Prerequisite   : ADO Multi-Stage Yaml Pipeline
# -----------------------------------------------------------------------------

name: Bastion-$(Date:yyyyMMdd).$(Rev:.r)

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - infra/terraform/bastion-net/*

variables:
  - name: ado_agent_pool
    value: 'Azure Pipelines'
  - name: ado_service_connection_name
    value: 'Azure Subscription'
  - name: environment
    value: dev
  - name: location
    value: eastus2
  - name: prefix
    value: alebastion
  - name: resource_group
    value: $(prefix)-$(environment)-rg
  - name: storagekey
    value: PipelineWillGetThisValueRuntime
  - name: terraformstorageaccount
    value: tfalebastiondevsa
  - name: terraformstoragerg
    value: tf-$(prefix)-$(environment)-rg
  - name: vm_username
    value: vmadmin
  - name: vm_password
    value: DevOps!01
  - name: ado_pool_name
    value: UbuntuPrivatePool
  - name: ado_server_url
    value: $(System.TeamFoundationCollectionUri)
  - name: ado_pat_token
    value: $(System.AccessToken)

stages: 
  - stage: Build
    displayName: Build  
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: ${{ variables.ado_agent_pool }}
        steps:
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(build.artifactstagingdirectory)/terraform'
          inputs:
            SourceFolder: 'infra/terraform/bastion-net'
            TargetFolder: '$(build.artifactstagingdirectory)/terraform'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: infra'
          inputs:
            ArtifactName: infra

  - stage: dev
    displayName: dev
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          name: ${{ variables.ado_agent_pool }}
        steps:   
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'infra'
            downloadPath: '$(System.ArtifactsDirectory)/_artifacts'

        - task: AzureCLI@1
          displayName: 'Azure CLI to deploy required Azure resources (Terraform State)'
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            scriptLocation: inlineScript
            inlineScript: |
              # this will create Azure resource group
              az group create --location $(location) --name $(terraformstoragerg)
              
              az storage account create --name $(terraformstorageaccount) --resource-group $(terraformstoragerg) --location $(location) --sku Standard_LRS --kind StorageV2
              
              az storage container create --name terraform --account-name $(terraformstorageaccount)
              
              set KEY=$(az storage account keys list -g $(terraformstoragerg) -n $(terraformstorageaccount) --query "[0].value" -o tsv)
              
              echo "##vso[task.setvariable variable=storagekey]$KEY"

        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in terraform file'
          inputs:
            targetFiles: '**/*.tf'
            escapeType: none
            tokenPrefix: '__'
            tokenSuffix: '__'

        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in terraform vars file'
          inputs:
            targetFiles: '**/*.tfvars'
            escapeType: none
            tokenPrefix: '__'
            tokenSuffix: '__'

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          displayName: 'Install Terraform 0.12.9'
          inputs:
            terraformVersion: 0.12.9

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : init'
          inputs:
            workingDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/infra/terraform'
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: terraform
            backendAzureRmKey: terraform.tfstate

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : plan'
          inputs:
            command: plan
            workingDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/infra/terraform'
            environmentServiceNameAzureRM: ${{ variables.ado_service_connection_name }}
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: terraform
            backendAzureRmKey: terraform.tfstate

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : apply -auto-approve'
          inputs:
            command: apply
            workingDirectory: '$(System.DefaultWorkingDirectory)/_Demo-Bastion-Infra-CI/infra/terraform'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: ${{ variables.ado_service_connection_name }}
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: terraform
            backendAzureRmKey: terraform.tfstate
