# -----------------------------------------------------------------------------
# .SYNOPSIS
#   This is the main pipeline for Private AKS App Deployment. 
#   The main pipeline will orchestrate the build and deploy to environments. 

# .DESCRIPTION
#   This pipeline will perform setup tasks for the image by:
#   1. Docker Compose Build and Push to Azure Container Registry
#   2. Find and replace token (variables) in .yaml files.
#   3. Kubectl apply yaml

# .ASSUMPTIONS:
#     1. You are referencing this template from an ado pipeline

# .NOTES
#     File Name      : azure-pipelines.yml
#     Prerequisite   : ADO Multi-Stage Yaml Pipeline
# -----------------------------------------------------------------------------

name: AKS-App-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - app/*

variables:
  - group: aks_dev_vars
  
  - name: ado_agent_pool
    value: 'UbuntuPrivatePool'
  - name: ado_service_connection_name
    value: 'Azure Subscription'

stages: 
  - stage: Build
    displayName: Build  
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: ${{variables.ado_agent_pool }}
        steps:
        - task: DockerCompose@0
          displayName: 'Run a Docker Compose - Build'
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            azureContainerRegistry: '$(acr)'
            dockerComposeFile: 'app/docker-compose.yaml'
            action: 'Build services'
            additionalImageTags: $(Build.BuildId)
            includeLatestTag: true
            dockerComposeFileArgs: |
              TAG=$(environment)
              REGISTRY=$(acr)

        - task: DockerCompose@0
          displayName: 'Run a Docker Compose - Push '
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            azureContainerRegistry: '$(acr)'
            dockerComposeFile: 'app/docker-compose.yaml'
            action: 'Push services'
            additionalImageTags: $(Build.BuildId)
            includeLatestTag: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: app'
          inputs:
            PathtoPublish: app
            ArtifactName: app

  - stage: dev
    displayName: dev
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          name: ${{ variables.ado_agent_pool }}
        steps:   
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'app'
            downloadPath: '$(System.DefaultWorkingDirectory)/_artifacts'

        - task: AzureCLI@1
          displayName: 'Azure CLI to get AKS credentials'
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            scriptLocation: inlineScript
            inlineScript: 'az aks get-credentials -n $(aks_name) -g $(resource_group) --overwrite-existing'

        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in **/*.yaml'
          inputs:
            rootDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/app'
            targetFiles: '**/*.yaml'
            tokenPrefix: '${__'
            tokenSuffix: '__}'

        - task: KubectlInstaller@0
          displayName: 'Install Kubectl latest'

        - task: Kubernetes@1
          displayName: 'kubectl apply'
          inputs:
            connectionType: 'Azure Resource Manager'
            azureSubscriptionEndpoint: ${{ variables.ado_service_connection_name }}
            azureResourceGroup: '$(resource_group)'
            kubernetesCluster: '$(aks_name)'
            namespace: default
            command: apply
            arguments: '-f $(System.DefaultWorkingDirectory)/_artifacts/app/azure-vote-all-in-one-redis.yaml  --overwrite=true --validate=false'
            azureSubscriptionEndpointForSecrets: ${{ variables.ado_service_connection_name }}
            azureContainerRegistry: '$(acr)'
            secretName: 'acr-auth'

        - task: HelmInstaller@1
          displayName: Helm installer 3.0.0
          inputs: 
            helmVersionToInstall: 3.0.0

        - task: Bash@3
          displayName: 'Bash Script to Add Helm repos'
          inputs:
            targetType: 'inline'
            script: |
              helm repo add stable https://kubernetes-charts.storage.googleapis.com/
              helm repo update
        # helm install my-nginx-ingress stable/nginx-ingress -f $(System.DefaultWorkingDirectory)/_artifacts/app/internal-ingress.yaml --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux --wait

        - task: HelmDeploy@0
          displayName: Helm install NGINX
          inputs:
            azureSubscriptionEndpoint: ${{ variables.ado_service_connection_name }}
            azureResourceGroup: '$(resource_group)'
            kubernetesCluster: '$(aks_name)'
            namespace: default
            command: 'upgrade'
            install: true
            releaseName: 'my-nginx-ingress'
            chartType: 'Name'
            chartName: 'stable/nginx-ingress'
            overrideValues: 'controller.nodeSelector."beta\.kubernetes\.io/os"=linux,defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux'
            arguments: '-f $(System.DefaultWorkingDirectory)/_artifacts/app/internal-ingress.yaml'

        - task: AzureCLI@1
          displayName: 'Azure CLI to set Private Link Service for Ingress'
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            scriptLocation: inlineScript
            inlineScript: |
              # Create Private Link Service
              AKS_NODE_RG_NAME=$(az aks show --resource-group $(resource_group) --name $(aks_name) --query "nodeResourceGroup" --output tsv)
              LB_FRONTEND_IP_CONFIG=$(az network lb show -g $AKS_NODE_RG_NAME -n "kubernetes-internal" --query "frontendIpConfigurations[0].id" -o tsv)
              az network private-link-service create -g $(resource_group) -n "$(prefix)-$(environment)-intlb-pls" --vnet-name $(vnet_name) --subnet "proxy-subnet" --lb-frontend-ip-configs $LB_FRONTEND_IP_CONFIG --location $LOCATION 
        
              PLS_ID=$(az network private-link-service show -g $(resource_group) --name "$(prefix)-$(environment)-intlb-pls" --query "id" -o tsv)
              SUBNET_ID=$(az network vnet subnet show -g $(pe_rg_name) -n $(pe_subnet_name) --vnet-name $(pe_vnet_name) --query 'id' -o tsv)
              az network vnet subnet update --name $(pe_subnet_name) --resource-group $(pe_rg_name) --vnet-name $(pe_vnet_name) --disable-private-endpoint-network-policies true
              az network private-endpoint create --name "$(prefix)-$(environment)-intlb-pe" --resource-group $(pe_rg_name) --subnet $SUBNET_ID --private-connection-resource-id $PLS_ID --connection-name "$(prefix)-$(environment)-intlb-connection" --manual-request false
